# fly.toml app configuration file generated for ohtukandiviitteet on 2023-11-17T11:51:10+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ohtukandiviitteet"
primary_region = "arn"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "5000"

[[services]]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
